CREATE SCHEMA IF NOT EXISTS stufamily;
SET SCHEMA stufamily;

CREATE TYPE user_type AS ENUM ('ADMIN', 'WECHAT', 'HYBRID');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'DISABLED', 'LOCKED');
CREATE TYPE product_type AS ENUM ('FAMILY_CARD', 'VALUE_ADDED_SERVICE');
CREATE TYPE publish_status AS ENUM ('DRAFT', 'ON_SHELF', 'OFF_SHELF');
CREATE TYPE duration_type AS ENUM ('MONTH', 'SEMESTER', 'YEAR');
CREATE TYPE order_type AS ENUM ('FAMILY_CARD', 'VALUE_ADDED_SERVICE');
CREATE TYPE order_status AS ENUM ('PENDING_PAYMENT', 'PAID', 'CANCELLED', 'EXPIRED', 'REFUNDED');
CREATE TYPE payment_status AS ENUM ('INITIATED', 'SUCCESS', 'FAILED', 'CLOSED', 'REFUNDED');
CREATE TYPE member_status AS ENUM ('ACTIVE', 'EXPIRED', 'CANCELLED');
CREATE TYPE group_status AS ENUM ('ACTIVE', 'CLOSED');
CREATE TYPE message_status AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE entitlement_status AS ENUM ('ACTIVE', 'EXPIRED', 'USED_UP', 'CANCELLED');

CREATE TABLE sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_no VARCHAR(32) NOT NULL UNIQUE,
    user_type user_type NOT NULL DEFAULT 'WECHAT',
    status user_status NOT NULL DEFAULT 'ACTIVE',
    token_version BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(64),
    password_hash VARCHAR(255),
    openid VARCHAR(64) UNIQUE,
    unionid VARCHAR(64),
    nickname VARCHAR(100),
    avatar_url TEXT,
    phone VARCHAR(32),
    email VARCHAR(128),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_user_type_status ON sys_user (user_type, status);
CREATE INDEX idx_sys_user_phone ON sys_user (phone);

CREATE TABLE sys_admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_no VARCHAR(32) NOT NULL UNIQUE,
    status user_status NOT NULL DEFAULT 'ACTIVE',
    token_version BIGINT NOT NULL DEFAULT 0,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(100),
    avatar_url TEXT,
    phone VARCHAR(32),
    email VARCHAR(128),
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sys_admin_user_status ON sys_admin_user (status);

CREATE TABLE sys_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL REFERENCES sys_user(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES sys_role(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE visibility_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(80) NOT NULL UNIQUE,
    allow_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
    require_login BOOLEAN NOT NULL DEFAULT FALSE,
    require_family_registered BOOLEAN NOT NULL DEFAULT FALSE,
    require_active_family_card BOOLEAN NOT NULL DEFAULT FALSE,
    require_value_added_entitlement BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE service_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(40) NOT NULL UNIQUE,
    category_name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    sort_order INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_no VARCHAR(40) NOT NULL UNIQUE,
    product_type product_type NOT NULL,
    title VARCHAR(200) NOT NULL,
    subtitle VARCHAR(255),
    detail_content TEXT NOT NULL,
    image_urls VARCHAR(2000) NOT NULL DEFAULT '[]',
    contact_name VARCHAR(100),
    contact_phone VARCHAR(32),
    service_start_at TIMESTAMP,
    service_end_at TIMESTAMP,
    sale_start_at TIMESTAMP,
    sale_end_at TIMESTAMP,
    publish_status publish_status NOT NULL DEFAULT 'DRAFT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    is_top BOOLEAN NOT NULL DEFAULT FALSE,
    display_priority INT NOT NULL DEFAULT 0,
    list_visibility_rule_id BIGINT REFERENCES visibility_rule(id),
    detail_visibility_rule_id BIGINT REFERENCES visibility_rule(id),
    category_id BIGINT REFERENCES service_category(id),
    created_by BIGINT REFERENCES sys_user(id),
    updated_by BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_product_list ON product (product_type, publish_status, is_top, display_priority DESC);

CREATE TABLE product_family_card_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    duration_type duration_type NOT NULL,
    duration_months INT NOT NULL CHECK (duration_months > 0),
    price_cents BIGINT NOT NULL CHECK (price_cents >= 0),
    max_family_members INT NOT NULL CHECK (max_family_members > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, duration_type)
);

CREATE TABLE product_value_added_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    sku_no VARCHAR(40) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    unit_name VARCHAR(40) NOT NULL DEFAULT 'item',
    price_cents BIGINT NOT NULL CHECK (price_cents >= 0),
    max_purchase_qty INT NOT NULL DEFAULT 1 CHECK (max_purchase_qty > 0),
    service_notice TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_main (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    buyer_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    order_type order_type NOT NULL,
    order_status order_status NOT NULL DEFAULT 'PENDING_PAYMENT',
    total_amount_cents BIGINT NOT NULL CHECK (total_amount_cents >= 0),
    discount_amount_cents BIGINT NOT NULL DEFAULT 0 CHECK (discount_amount_cents >= 0),
    payable_amount_cents BIGINT NOT NULL CHECK (payable_amount_cents >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    source_channel VARCHAR(32) NOT NULL DEFAULT 'WEIXIN_MINIAPP',
    client_ip VARCHAR(40),
    expire_at TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    cancel_reason VARCHAR(255),
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_order_main_user_status ON order_main (buyer_user_id, order_status, created_at DESC);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES order_main(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES product(id),
    product_type_snapshot product_type NOT NULL,
    product_title_snapshot VARCHAR(200) NOT NULL,
    product_brief_snapshot VARCHAR(255),
    product_detail_snapshot VARCHAR(2000) NOT NULL DEFAULT '{}',
    selected_duration_type duration_type,
    selected_duration_months INT,
    service_start_at TIMESTAMP,
    service_end_at TIMESTAMP,
    unit_price_cents BIGINT NOT NULL CHECK (unit_price_cents >= 0),
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    total_price_cents BIGINT NOT NULL CHECK (total_price_cents >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR(50) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL UNIQUE REFERENCES order_main(id),
    payment_status payment_status NOT NULL DEFAULT 'INITIATED',
    channel VARCHAR(32) NOT NULL DEFAULT 'WECHAT_PAY',
    appid VARCHAR(64),
    mchid VARCHAR(64),
    out_trade_no VARCHAR(64) NOT NULL UNIQUE,
    transaction_id VARCHAR(64) UNIQUE,
    trade_type VARCHAR(32),
    payer_openid VARCHAR(64),
    bank_type VARCHAR(32),
    total_amount_cents BIGINT NOT NULL CHECK (total_amount_cents >= 0),
    payer_total_cents BIGINT CHECK (payer_total_cents IS NULL OR payer_total_cents >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'CNY',
    notify_payload VARCHAR(2000),
    notify_signature TEXT,
    notify_sign_type VARCHAR(16),
    success_time TIMESTAMP,
    fail_reason VARCHAR(255),
    product_type_snapshot product_type,
    product_title_snapshot VARCHAR(200),
    product_meta_snapshot VARCHAR(2000) NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_payment_status_created ON payment_transaction (payment_status, created_at DESC);

CREATE TABLE service_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE REFERENCES order_main(id) ON DELETE CASCADE,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    buyer_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    product_id BIGINT REFERENCES product(id),
    product_type product_type,
    stars INT NOT NULL CHECK (stars BETWEEN 1 AND 5),
    content VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_service_review_buyer_created ON service_review (buyer_user_id, created_at DESC);

CREATE TABLE family_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_no VARCHAR(40) NOT NULL UNIQUE,
    source_order_id BIGINT NOT NULL UNIQUE REFERENCES order_main(id),
    owner_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    family_card_product_id BIGINT NOT NULL REFERENCES product(id),
    family_card_plan_id BIGINT REFERENCES product_family_card_plan(id),
    max_members INT NOT NULL CHECK (max_members > 0),
    current_members INT NOT NULL DEFAULT 0 CHECK (current_members >= 0),
    status group_status NOT NULL DEFAULT 'ACTIVE',
    activated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE family_member_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES family_group(id) ON DELETE CASCADE,
    member_no VARCHAR(40) NOT NULL UNIQUE,
    bound_user_id BIGINT REFERENCES sys_user(id),
    member_name VARCHAR(100) NOT NULL,
    student_or_card_no VARCHAR(64) NOT NULL,
    phone VARCHAR(32),
    card_received_date DATE NOT NULL,
    relation_to_owner VARCHAR(32),
    added_by_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    status member_status NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    cancel_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (group_id, student_or_card_no)
);

CREATE INDEX idx_family_member_group_status ON family_member_card (group_id, status);
CREATE INDEX idx_family_member_name ON family_member_card (member_name);

CREATE TABLE family_checkin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkin_no VARCHAR(40) NOT NULL UNIQUE,
    group_id BIGINT NOT NULL REFERENCES family_group(id) ON DELETE CASCADE,
    owner_user_id BIGINT NOT NULL REFERENCES sys_user(id),
    family_member_id BIGINT REFERENCES family_member_card(id) ON DELETE SET NULL,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    address_text VARCHAR(255) NOT NULL,
    checked_in_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_family_checkin_owner_checked ON family_checkin (owner_user_id, checked_in_at DESC);
CREATE INDEX idx_family_checkin_group_checked ON family_checkin (group_id, checked_in_at DESC);

CREATE TABLE homepage_banner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    image_url TEXT NOT NULL,
    link_type VARCHAR(30) NOT NULL DEFAULT 'NONE',
    link_target TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    created_by BIGINT REFERENCES sys_user(id),
    updated_by BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE site_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    community_name VARCHAR(150) NOT NULL,
    banner_slogan VARCHAR(200),
    intro_text TEXT,
    contact_person VARCHAR(64),
    contact_phone VARCHAR(32),
    contact_wechat VARCHAR(64),
    contact_wechat_qr_url TEXT,
    address_text VARCHAR(255),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    ext VARCHAR(2000) NOT NULL DEFAULT '{}',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by BIGINT REFERENCES sys_user(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE home_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    content TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_home_notice_enabled_time ON home_notice (enabled, sort_order DESC, id DESC);

CREATE TABLE parent_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES sys_user(id),
    parent_id BIGINT,
    root_id BIGINT,
    sender_type VARCHAR(20) NOT NULL DEFAULT 'USER',
    nickname_snapshot VARCHAR(100),
    avatar_snapshot TEXT,
    content TEXT NOT NULL,
    status message_status NOT NULL DEFAULT 'PENDING',
    viewed BOOLEAN NOT NULL DEFAULT FALSE,
    viewed_at TIMESTAMP,
    replied_at TIMESTAMP,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    review_note VARCHAR(255),
    reviewed_by BIGINT REFERENCES sys_user(id),
    reviewed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_parent_message_user ON parent_message(user_id, id);
